### ISSUE TITLE
CSS Format?

### ISSUE THREAD

**Issue by Puppin** [vsilva472/jquery-table-sorter#2]
Dear @vsilva472, thank you for the nice script. Can you tell more about CSS. How can I change unicode symbols to let say awesome icons like fa fa-chevron-circle-up/down

**Comment by vsilva472** [comment]
Hi @Puppin!  how are you? Thanks for ask!!  
You can use font-awesome icons just like the unicode icons! It is easy ;)  
Take look at this piece of code:  
```php
$( '#my-table-selector' ).TableSorter({
     arrows: { 
          up:  '<i class="fas fa-chevron-circle-up"></i>', 
          down: '<i class="fas fa-chevron-circle-down"></i>' 
     }
});
```
And to improve user experience, just add this CSS in your code:
```css
#my-table-selector th {
  cursor: pointer;
}

.ts-sort-indicator {
  display: inline-block;
  margin-left: 5px;
}
```

Just remember to change `#my-table-selector` to your table selector in both (js/css) pieces of code.  
Let me know if the result is what you want.
